version: "3"

services:
  app_proxy:
    environment:
      APP_HOST: entity-auto-mcs_app_1
      APP_PORT: 8080

  app:
    image: macarooniman/auto-mcs:2.3.4@sha256:d8bdf17740cbc3efc8a0baf1127ad2f1fe0a3d9afc175f2998b529c4049a6fa3
    container_name: auto-mcs
    stdin_open: true
    tty: true
    restart: unless-stopped

    environment:

      # Default web interface port
      WEB_PORT: "8080"

      # Change the web interface credentials
      WEB_USERNAME: "root"
      WEB_PASSWORD: "auto-mcs"

    stdin_open: true
    tty: true
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/root/.auto-mcs
    ports:
      - "7001:7001"
      - "25565:25565"
